name: Deploy to Azure ACI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Compilação
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Configura jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compilação
      run: mvn clean install -DskipTests

  code-quality:
    name: Qualidade de código
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Adicionando Permissao para o mvnw
      run: chmod +x mvnw
    - name: Análise SonarCloud
      run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=lab-crescer-pipeline
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  tests: 
    name: Testes Automatizados
    needs: code-quality
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: Configura jdk 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Testes Unitários
      run: mvn -B test --file pom.xml
  
  push-image:
    name: Enviando imagem para o docker hub
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: login docker hub
      uses: dicker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Criacao e envio de imagem
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile
        push: true
        run: |
          export DOCKER_BUILDKIT=0
          export COMPOSE_DOCKER_CLI_BUILD=0
        tags:
          caetanobraga/javacrescer:latest
  
  deploy:
    name: Publica App ACI
    needs: push-image
    runs-on: ubuntu-latest
    steps:
    - name: Login no Azure CLI
      uses: azure/login@v1
      with:
        creeds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Application to Azure 
      uses: azure/aci-deploy@v1
      with:
        resource-group: RG-APPS-CRESCER
        dns-name-label: lab-crescer-caetano-braga
        image: caetanobraga/javacrescer:latest
        cpu: 1
        mamory: 1
        registry-login-server: docker.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: lab-crescer-caetano-braga
        location: 'east us'
